"""initial schema

Revision ID: 58c20adbd18d
Revises: 
Create Date: 2026-02-21 18:01:54.893769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c20adbd18d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('registry', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registry', 'external_id', name='uq_org_registry_external_id')
    )
    op.create_table('grants',
    sa.Column('funder_org_id', sa.Uuid(), nullable=False),
    sa.Column('grantee_org_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['funder_org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['grantee_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grants_funder', 'grants', ['funder_org_id'], unique=False)
    op.create_index('ix_grants_funder_grantee', 'grants', ['funder_org_id', 'grantee_org_id'], unique=False)
    op.create_index('ix_grants_grantee', 'grants', ['grantee_org_id'], unique=False)
    op.create_table('tenants',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('linked_org_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['linked_org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('funnel_entries',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('prospect', 'shortlisted', 'researching', 'application_in_progress', 'funded', 'passed', name='funnelstatus'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'org_id', name='uq_funnel_tenant_org')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funnel_entries')
    op.drop_table('tenants')
    op.drop_index('ix_grants_grantee', table_name='grants')
    op.drop_index('ix_grants_funder_grantee', table_name='grants')
    op.drop_index('ix_grants_funder', table_name='grants')
    op.drop_table('grants')
    op.drop_table('organizations')
    # ### end Alembic commands ###
